[package]
name = "B-Strings_with_the_Same_Length"
version = "0.1.0"
authors = ["Hiroya_W <e8239@g.maizuru-ct.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
